# Generated by Django 4.0.5 on 2022-06-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('oId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('percentOff', models.IntegerField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
