# Generated by Django 4.0.5 on 2022-06-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('sId', models.AutoField(primary_key=True, serialize=False)),
                ('slotDate', models.DateField()),
                ('slotTime', models.TimeField()),
                ('slotAvailable', models.IntegerField()),
            ],
        ),
    ]
