# Generated by Django 4.0.5 on 2022-07-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slotAvailable',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slotDate',
        ),
    ]
