# Generated by Django 4.0.5 on 2022-07-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_slot_slotavailable_remove_slot_slotdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slotRemaining',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slotTime',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bId', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('cId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customers')),
                ('sId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.slot')),
            ],
        ),
    ]
