# Generated by Django 4.0.5 on 2022-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_slot_slotremaining_alter_slot_slottime_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('sId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
    ]
