# Generated by Django 4.0.5 on 2022-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_slot_slotdate_alter_slot_slottime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dateCreated',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
