# Generated by Django 4.0.5 on 2022-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_booking_datecreated_booking_bookingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('orderTotal', models.FloatField()),
            ],
        ),
    ]
