# Generated by Django 4.0.5 on 2022-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
