# Generated by Django 4.0.5 on 2022-07-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='token',
            field=models.IntegerField(null=True),
        ),
    ]
