# Generated by Django 4.0.5 on 2022-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('uId', models.AutoField(primary_key=True, serialize=False)),
                ('update', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
